# Generated by Django 5.2.1 on 2025-05-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
