# Generated by Django 3.2.19 on 2025-05-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_alter_negocio_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
