# Generated by Django 3.2.19 on 2025-05-20 01:54

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicio_negocio'),
        ('negocio', '0001_initial'),  # Asegurarse que la app negocio esté instalada
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='negocio',
            field=models.ForeignKey(
                to='negocio.negocio',
                on_delete=models.CASCADE,
                related_name='servicios',
                null=True,
                blank=True
            ),
        ),
    ]
