# Generated by Django 5.2.1 on 2025-05-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
    ]
