# Generated by Django 3.2.19 on 2025-05-19 00:47

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negocio', '0003_alter_negocio_telefono'),
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100)),
                ('experiencia_anios', models.IntegerField()),
                ('foto_perfil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_perfil')),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.negocio')),
                ('rol', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rol.rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
