# Generated by Django 5.2.1 on 2025-05-17 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
            },
        ),
    ]
